In [5]:
import numpy as np
import cv2


In [3]:
from ultralytics import YOLO

In [4]:
import cvzone
import math
model=YOLO("yolov8n.pt")

In [1]:
from sort import *

C:\Users\yash\anaconda3\Lib\site-packages\paramiko\transport.py:219: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,


In [6]:
import cvzone
import math
model=YOLO("yolov8n.pt")
classNames =["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat", "traffic light", 
             "fire nydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", 
             "cow", "elephant", "bear", "Zebra", "giraffe", "backpack", "umbrella", "handbag" "tie", 
             "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "haseball bat",
             
             "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass",
             "cup", "fork", "knife", "spoon", "bowt", 
             "banana", "apple", "sandwich", "orange", "broccoli", "carrot", "hot dog",
             "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed", 
             "diningtable", "toilet", "tvmonitor", "Laptop", "mouse", 
             "remote", "keyboard", "cell phone", "cellphone", "oven", 
             "toaster", "sink", "refrigeraton", "book", "clock", "vase", 
             "scissors", "teddy bear", "hair drier","toothbrush"]


tracker=Sort(max_age=20,min_hits=3,iou_threshold=0.3)
limits=[723,500,1473,500]
totalCount=[]

cap=cv2.VideoCapture('13.mp4')
cap.set(3,640)
cap.set(4,480)
mask=cv2.imread("mask_car.png")
while True:
    success,img=cap.read()
    mask_resized = cv2.resize(mask, (img.shape[1], img.shape[0]))  # Match width and height of img
    imgRegion = cv2.bitwise_and(img, mask_resized)

#     imgRegion=cv2.bitwise_and(img,mask)
    results=model(imgRegion,stream=True)
    detections=np.empty((0,5))
    for r in results:
        boxes=r.boxes
        for box in boxes:
            #bounding box
            
            x1,y1,x2,y2=box.xyxy[0]

            x1,y1,x2,y2=int(x1),int(y1),int(x2),int(y2)
#             cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),3)
            w,h=x2-x1,y2-y1
#             bbox=int(x1),int(y1),int(w),int(h)
            
            
            
            print(x1,y1,x2,y2)

            cvzone.cornerRect(img,(x1,y1,w,h),l=15,colorR=(0, 0, 255),colorC=(0, 255, 255))
#             confidence
            conf=math.ceil((box.conf[0]*100))/100
                            
            print(conf)
            cls=int(box.cls[0])
            currentclass=classNames[cls]
            if currentclass=='car'or currentclass=='bus'or currentclass=='truck' or currentclass=='motorbiker' and conf>0.3:
                
#                 cvzone.putTextRect(img,f'{classNames[cls]} {conf}',(max(0,x1),max(15,y1)),scale=1,thickness=1,colorT=(0, 0, 255),
#                                colorR=(255, 0,0),offset=3)
                cvzone.cornerRect(img,(x1,y1,w,h),l=15,rt=1,colorR=(0, 0, 255),colorC=(0, 255, 255))
                currentArray=np.array([x1,y1,x2,y2,conf])
                detections=np.vstack((detections,currentArray))
                
                
    resultTracker=tracker.update(detections)
    cv2.line(img,(limits[0],limits[1]),(limits[2],limits[3]),(0,0,250),thickness=5)
    for result in resultTracker:
        x1,y1,x2,y2,id=result
        x1,y1,x2,y2=int(x1),int(y1),int(x2),int(y2)
        print(result)
        w,h=x2-x1,y2-y1
        
        cvzone.cornerRect(img,(x1,y1,w,h),l=15,rt=1,colorR=(100, 255, 255),colorC=(0, 150, 255))
        cvzone.putTextRect(img,f'{classNames[cls]} {conf}',(max(0,x1),max(35,y1)),scale=1,thickness=2,colorT=(0, 0, 255),
                               colorR=(255, 0,0),offset=3)
        cx,cy=x1+w//2,y1+h//2
        cv2.circle(img,(cx,cy),5,(255,0,255),cv2.FILLED)
        
        if limits[0]<cx<limits[2] and limits[1]-20<cy<limits[1]+20:
            if totalCount.count(id)==0:
                
            
                totalCount.append(id)
    cvzone.putTextRect(img,f'COUNT:{len(totalCount)}',(50,50),scale=1,thickness=2,colorT=(0, 0, 255),
                               colorR=(255, 0,0),offset=3)
        
    cv2.imshow("images",img)
#     cv2.imshow("imagesRegion",imgRegion)
    cv2.waitKey(1)
        # Wait for 1ms, check if 'q' key is pressed
    key = cv2.waitKey(1)
    if key == 27:  # 'q' key to quit
        break


cap.release()
cv2.destroyAllWindows()



0: 384x640 6 persons, 10 cars, 2 trucks, 136.5ms
836 504 918 586
0.88
0 686 349 880
0.82
28 568 259 700
0.8
1446 659 1492 780
0.73
1511 669 1556 786
0.72
523 535 694 627
0.7
1426 522 1460 607
0.67
752 449 834 515
0.64
1278 500 1308 581
0.54
239 587 446 708
0.52
1596 668 1634 745
0.51
465 640 635 773
0.47
420 519 525 606
0.43
1850 512 1919 591
0.39
592 406 624 459
0.34
961 434 1001 495
0.31
563 484 645 538
0.3
1017 463 1068 532
0.27
Speed: 5.0ms preprocess, 136.5ms inference, 7.0ms postprocess per image at shape (1, 3, 384, 640)
[       1017         463        1068         532          12]
[        563         484         645         538          11]
[        961         434        1001         495          10]
[       1850         512        1919         591           9]
[        420         519         525         606           8]
[        465         640         635         773           7]
[        239         587         446         708           6]
[        752         449       

[      953.6      439.21       999.7       500.3          10]
[     1850.3       510.6      1919.2      591.31           9]
[     379.81       659.9      572.64       805.3           7]
[     142.49      600.08      376.56      739.74           6]
[     733.29      455.79      821.21      523.25           5]
[     469.36      545.93      648.63      642.01           4]
[      -7.93      585.38      199.39      718.51           3]
[    -8.7693      724.41       259.7      914.83           2]
[     826.56      515.56      913.43      601.47           1]

0: 384x640 8 persons, 11 cars, 2 trucks, 1 boat, 83.9ms
827 516 913 603
0.89
0 728 234 919
0.79
464 548 645 644
0.78
1508 653 1551 775
0.75
732 457 818 524
0.74
0 583 186 727
0.7
124 603 365 751
0.69
1444 650 1490 767
0.67
1429 523 1465 608
0.55
1277 501 1304 576
0.47
365 662 563 818
0.42
1496 631 1551 777
0.41
1607 669 1656 742
0.38
1852 510 1919 592
0.34
951 443 998 502
0.33
1483 550 1785 669
0.33
1030 423 1091 468
0.32
1430 495 1469 6

[    -4.6739      750.25      140.92      894.61          22]
[     286.88      684.11      476.37      835.72          21]
[    -1.8626       601.4      127.92      725.58          20]
[     1034.1       421.5      1089.1      467.11          18]
[     1010.2       478.6      1065.2      554.78          12]
[     947.55      444.72         995      505.33          10]
[     1852.2      511.38      1919.1       590.7           9]
[       46.5       618.2      303.27      779.14           6]
[      714.7         463      807.45         533           5]
[      409.9      558.12      604.74      658.62           4]
[     817.58      528.19      909.31      617.33           1]

0: 384x640 6 persons, 11 cars, 3 trucks, 96.5ms
815 530 910 620
0.79
1504 644 1550 769
0.74
711 465 805 535
0.74
398 559 602 658
0.7
36 622 290 786
0.7
1439 646 1488 760
0.61
1429 525 1464 610
0.58
0 752 117 906
0.57
324 535 435 635
0.46
274 687 463 838
0.43
0 600 116 724
0.42
1611 673 1660 755
0.42
1034 416 1088 46

[     1037.5      418.46      1090.6       466.8          18]
[     947.89      450.08      994.22      511.07          10]
[      284.9      542.78      402.27      643.61           8]
[     182.15      709.47      386.99      877.78           7]
[     696.81       473.4      794.12      545.64           5]
[      352.8      571.17      562.78       676.9           4]
[     807.71       541.5      907.52      639.04           1]

0: 384x640 7 persons, 13 cars, 1 truck, 1 boat, 81.8ms
694 475 792 547
0.81
341 570 557 679
0.75
1507 644 1550 764
0.72
805 543 906 641
0.69
167 711 373 882
0.6
1438 532 1470 613
0.6
1444 646 1492 750
0.53
0 642 215 819
0.53
1621 675 1659 755
0.51
276 545 395 643
0.47
883 441 932 500
0.38
1038 569 1110 677
0.38
1011 488 1074 568
0.38
552 421 581 467
0.35
0 644 217 819
0.35
791 435 858 493
0.35
1490 543 1794 664
0.34
950 450 995 512
0.33
1036 420 1090 468
0.31
1478 892 1532 937
0.3
920 415 968 462
0.26
1281 489 1309 570
0.26
Speed: 2.0ms preprocess, 81.8ms inf

0: 384x640 9 persons, 10 cars, 4 trucks, 2 boats, 80.8ms
671 480 779 561
0.76
284 588 509 698
0.66
1449 637 1495 751
0.64
1448 532 1483 615
0.57
1039 420 1099 471
0.55
1511 641 1569 751
0.52
1017 500 1073 577
0.5
953 456 997 520
0.49
1481 879 1538 933
0.48
798 561 906 662
0.46
1629 675 1684 753
0.42
1510 645 1552 754
0.41
0 672 129 822
0.4
51 743 278 900
0.38
228 557 351 664
0.36
226 559 354 665
0.33
0 675 131 827
0.31
284 584 510 697
0.29
1803 681 1919 842
0.29
878 452 930 506
0.29
7 511 29 574
0.28
0 498 27 574
0.28
1287 482 1314 567
0.27
1498 542 1802 660
0.27
400 526 508 604
0.26
Speed: 2.0ms preprocess, 80.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[    -6.1845       674.4      136.48      821.25          25]
[     876.01      447.39      930.85      506.58          24]
[     1041.1      420.97      1097.9       469.5          18]
[     1015.9      499.66      1073.6      577.68          12]
[     952.09      455.54      997.17       518.8          10]
[ 

[     925.25      413.57      977.35      459.08          28]
[     868.86       447.3      926.79      507.49          24]
[     1045.9      418.46      1101.3      468.09          18]
[     1038.3      592.85      1122.1      699.26          16]
[       1015      498.94      1072.8      582.58          12]
[     951.32      452.68      997.53      521.63          10]
[    -15.461       772.6      191.26      922.22           7]
[     652.36       486.5      761.97      567.15           5]
[     229.17      597.11      464.57      713.79           4]
[     784.52      570.59      900.24      682.26           1]

0: 384x640 9 persons, 13 cars, 1 truck, 2 boats, 79.1ms
648 490 759 573
0.75
1513 637 1550 742
0.73
220 601 464 723
0.63
1453 629 1493 739
0.61
782 576 900 694
0.61
1458 531 1491 620
0.55
1486 848 1542 914
0.54
0 782 164 926
0.49
1046 425 1099 470
0.46
1035 599 1123 707
0.44
950 462 999 526
0.43
1014 488 1074 593
0.39
1291 469 1323 559
0.39
619 417 642 458
0.37
1548 633 1585 7

[     1046.3      422.82      1101.5      475.02          18]
[     1030.7      614.32      1122.2      727.09          16]
[     1008.9       496.2        1072      599.37          12]
[     331.55      539.39      448.31      629.55          11]
[     946.08      464.24       993.5      529.97          10]
[     125.88      577.88      263.26      690.77           8]
[    -22.329      805.52      78.116      940.45           7]
[      621.3      490.82      736.55      581.74           5]
[     161.85       611.3      415.06      737.69           4]
[     767.92      596.63      893.43      724.08           1]

0: 384x640 7 persons, 14 cars, 1 truck, 2 boats, 85.1ms
766 599 894 732
0.88
146 615 411 746
0.84
618 499 736 587
0.83
1517 627 1560 737
0.67
1052 426 1103 476
0.52
1491 849 1545 899
0.51
1456 630 1498 735
0.5
327 543 446 630
0.48
949 466 999 534
0.45
120 580 258 698
0.45
1037 622 1123 736
0.39
1566 636 1598 727
0.38
0 824 40 934
0.38
1468 532 1503 617
0.38
1819 673 1918 803
0


0: 384x640 9 persons, 9 cars, 1 truck, 1 boat, 81.9ms
589 510 715 599
0.84
749 629 891 779
0.8
83 628 363 773
0.73
1520 626 1561 730
0.62
292 546 415 644
0.6
1580 633 1618 724
0.55
1467 619 1512 725
0.51
67 590 214 713
0.49
1501 829 1555 878
0.43
935 419 992 473
0.43
954 467 1010 540
0.37
12 508 36 583
0.33
1309 462 1338 548
0.31
1 503 26 582
0.3
1040 642 1131 776
0.3
1836 671 1919 785
0.29
1663 681 1706 769
0.29
686 379 810 497
0.29
852 452 919 524
0.28
1487 534 1519 622
0.27
Speed: 2.9ms preprocess, 81.9ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[      691.8      376.33      808.14      499.39          38]
[     933.57      420.98      992.54      472.87          28]
[     68.468      591.19      212.62      712.49          19]
[     1039.4      647.18      1131.2      767.72          16]
[     292.99      546.63      415.16       643.2          11]
[     954.47      467.97      1009.3      539.04          10]
[     590.73      509.84       714.7      599.48

[     5.1964      597.47      158.83       721.6          19]
[       1058      423.86      1115.8      477.14          18]
[     552.08      514.78      687.19      608.39           5]
[     7.5437      641.09      299.63      794.94           4]
[     719.54      665.72      874.44      834.35           1]

0: 384x640 5 persons, 9 cars, 1 truck, 1 boat, 80.9ms
712 671 872 845
0.85
545 515 682 610
0.78
0 644 290 801
0.76
1519 614 1561 720
0.65
1473 605 1516 716
0.6
0 597 151 730
0.46
0 493 32 578
0.45
685 436 770 493
0.41
1668 674 1715 757
0.39
1646 653 1678 723
0.38
1057 425 1116 478
0.37
1844 661 1919 772
0.36
242 552 372 677
0.36
835 451 905 523
0.32
948 471 1007 542
0.3
1030 672 1129 787
0.29
Speed: 3.0ms preprocess, 80.9ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[     684.24      436.64      769.96      492.67          41]
[      835.1      450.15      905.44      523.48          24]
[    -1.7118      599.19       151.9      726.14          19]
[     1057

[     665.11      433.87      750.54      489.87          41]
[     194.11       555.4      329.84      663.33          36]
[     1056.6      422.19      1118.7      480.21          18]
[       1018      706.89        1125      865.32          16]
[     195.87      554.92      329.43      662.33          11]
[     497.81      520.57      646.19      622.43           5]
[     670.84       721.6      848.77      919.04           1]

0: 384x640 7 persons, 9 cars, 1 truck, 1 boat, 83.4ms
658 727 845 935
0.89
489 521 641 627
0.78
1478 595 1518 700
0.6
1526 608 1562 708
0.57
661 434 744 490
0.54
1054 423 1120 482
0.52
1680 678 1724 765
0.51
0 662 221 823
0.43
1848 658 1919 774
0.41
1012 708 1123 878
0.39
186 557 322 661
0.38
185 556 324 664
0.36
1317 445 1344 526
0.35
1640 659 1674 733
0.32
933 423 1008 476
0.32
0 614 76 693
0.29
1564 614 1607 720
0.29
0 495 29 576
0.26
Speed: 2.0ms preprocess, 83.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[     660.87      433.85  

[    -5.0349      669.52      149.15      811.37          42]
[     641.36      429.07      724.45      488.83          41]
[     129.39      566.83      275.27      680.57          36]
[     784.21      455.15      866.76      539.52          24]
[     994.35      750.83      1111.5      926.69          16]
[     432.88      532.27      593.89      642.44           5]
[     609.19      785.25      811.67      949.14           1]

0: 384x640 6 persons, 7 cars, 1 truck, 173.1ms
603 808 810 937
0.75
0 674 134 813
0.74
420 532 589 645
0.73
121 567 268 684
0.57
1473 589 1513 693
0.55
1522 602 1561 699
0.52
1684 682 1728 775
0.51
639 428 720 488
0.47
992 758 1110 933
0.45
1617 639 1664 731
0.44
1507 767 1554 819
0.38
924 421 1017 484
0.37
1577 624 1610 723
0.32
785 451 866 538
0.26
Speed: 7.0ms preprocess, 173.1ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
[    -4.4802      674.87      138.22      810.31          42]
[     638.32      428.26       720.9      488.12    

[     621.43      415.42      701.15       476.8          41]
[     53.031      573.94      208.63      698.79          36]
[     1038.7      435.45      1110.8      494.98          18]
[     967.79         808      1099.2      945.85          16]
[     352.63      541.38      532.74      659.24           5]

0: 384x640 6 persons, 9 cars, 175.7ms
341 542 524 661
0.77
1469 579 1513 678
0.62
43 571 200 698
0.61
1520 588 1556 690
0.6
963 821 1099 937
0.6
1036 432 1109 495
0.54
1682 682 1731 773
0.52
1619 638 1660 747
0.47
1583 626 1614 723
0.44
621 415 696 477
0.42
965 562 1054 669
0.4
753 468 831 545
0.34
923 485 999 610
0.34
1315 437 1343 512
0.29
238 412 330 476
0.27
Speed: 5.0ms preprocess, 175.7ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     619.33      414.91      697.75      476.44          41]
[     43.781      572.65      200.46      698.65          36]
[     1036.8      433.95      1109.4      494.59          18]
[     964.49      814.14      1097.9    

0: 384x640 6 persons, 9 cars, 176.8ms
1021 438 1095 501
0.71
604 406 672 472
0.69
242 554 453 691
0.65
0 589 128 715
0.59
1465 576 1505 677
0.54
1518 580 1554 680
0.52
709 477 795 559
0.48
1617 642 1660 759
0.48
1680 686 1732 786
0.46
899 425 980 486
0.45
795 418 887 477
0.42
1582 623 1616 727
0.37
1495 740 1545 783
0.28
731 441 840 510
0.26
1086 401 1126 461
0.26
Speed: 6.0ms preprocess, 176.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[     242.41      554.43      453.15      690.22          55]
[     804.31      418.41      882.39      476.44          51]
[     898.56      423.26      982.04      485.21          50]
[     603.12      408.51      672.15      471.07          41]
[      -9.96      587.82      134.86      716.69          36]
[     1021.4      439.13      1096.3      500.34          18]

0: 384x640 5 persons, 9 cars, 174.6ms
233 557 443 695
0.7
0 592 119 715
0.61
1020 434 1093 503
0.58
1518 578 1552 683
0.57
1613 643 1659 753
0.57
1680 687 1732 78

[     145.86      575.18      375.45      723.99          55]
[     770.57      420.61      858.69      484.84          51]
[     923.89      627.31      1024.5      748.44          49]
[    -12.088      605.78      60.267      722.94          36]
[     1004.1      446.88      1084.8      515.18          18]
[     836.37      561.13      935.61      680.49          12]

0: 384x640 6 persons, 7 cars, 2 trucks, 171.0ms
1001 445 1085 516
0.79
133 576 369 728
0.78
1516 580 1553 683
0.55
1620 645 1662 776
0.52
1686 698 1741 798
0.51
0 612 43 723
0.5
923 634 1024 778
0.46
1459 567 1499 669
0.4
771 419 857 483
0.38
1488 725 1529 768
0.36
1584 629 1622 737
0.35
0 613 44 723
0.3
652 489 750 575
0.29
885 429 971 489
0.27
652 487 750 575
0.26
Speed: 4.5ms preprocess, 171.0ms inference, 3.3ms postprocess per image at shape (1, 3, 384, 640)
[     134.31      576.72      367.57      727.65          55]
[     769.09      419.49      857.39      484.21          51]
[     922.15      637.21        1024

[      875.5      522.62      955.82      619.69          65]
[     11.084      601.24      269.84       773.4          55]
[     734.88      428.39      821.22      494.55          51]
[     868.08      431.05      962.54      493.76          50]
[     986.13      460.49        1073      527.62          18]
[     782.58      606.95      887.41      731.98          12]

0: 384x640 7 persons, 14 cars, 1 truck, 184.1ms
984 462 1073 526
0.7
0 606 264 775
0.68
1515 572 1551 670
0.61
1691 704 1744 805
0.6
778 614 887 741
0.52
1618 651 1674 767
0.51
1588 635 1627 745
0.48
1458 563 1504 657
0.47
863 432 963 506
0.39
1315 432 1340 500
0.38
1089 409 1136 485
0.35
888 684 1003 849
0.34
734 432 807 494
0.33
324 406 373 442
0.31
877 521 957 625
0.3
860 433 957 531
0.29
858 455 939 532
0.28
652 454 778 540
0.27
1630 672 1675 770
0.27
736 430 834 494
0.27
877 522 957 626
0.26
371 395 470 446
0.26
Speed: 4.7ms preprocess, 184.1ms inference, 3.3ms postprocess per image at shape (1, 3, 384, 640)
[     

0: 384x640 6 persons, 12 cars, 1 bus, 3 trucks, 1 boat, 162.1ms
958 462 1060 540
0.8
1460 559 1501 658
0.6
855 734 980 908
0.53
856 541 941 656
0.53
1512 568 1547 663
0.52
723 663 843 820
0.45
843 438 938 501
0.43
1447 732 1576 873
0.42
1588 646 1633 755
0.4
1697 714 1750 806
0.4
0 635 172 811
0.39
529 513 641 612
0.38
1088 427 1135 498
0.38
827 468 906 550
0.37
1639 695 1679 781
0.37
0 636 173 812
0.35
687 432 813 499
0.34
0 635 174 811
0.32
824 441 910 543
0.29
325 404 374 443
0.29
1852 652 1919 770
0.28
1628 682 1677 779
0.27
373 394 470 448
0.26
Speed: 4.6ms preprocess, 162.1ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)
[    -5.6824      639.75      179.81      806.11          75]
[     -5.535      641.26      178.54      806.34          74]
[     324.16      404.42      374.48      442.48          67]
[     855.55      542.85      942.07      653.49          65]
[     855.58      734.76      979.94      901.18          63]
[     1088.1      427.33      1135.5

942 470 1049 547
0.77
827 789 965 935
0.64
0 658 90 801
0.62
670 713 808 890
0.62
1464 554 1502 652
0.54
1705 714 1755 824
0.52
610 388 660 440
0.45
836 441 930 511
0.44
1519 563 1551 662
0.42
695 434 798 508
0.42
475 521 597 630
0.42
798 456 887 558
0.39
1472 685 1521 726
0.38
1090 434 1139 505
0.36
1314 425 1344 493
0.32
324 403 380 440
0.27
Speed: 6.6ms preprocess, 178.4ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     610.57      387.98      660.07      439.77          79]
[    -5.0446      663.57      95.214      793.72          75]
[      798.3      464.21      887.05      555.61          71]
[     828.61      782.21      963.33      943.24          63]
[     694.67      436.03      797.26      506.96          51]
[     832.64      441.34      931.41      511.12          50]
[     943.36      469.69      1048.6      547.37          18]
[     672.97      715.73       806.7      884.63          12]

0: 384x640 5 persons, 12 cars, 1 truck, 180.2ms
940 471 104

0: 384x640 6 persons, 11 cars, 1 bus, 1 truck, 180.7ms
924 473 1034 562
0.86
598 791 760 937
0.8
1467 550 1506 640
0.59
1452 704 1580 844
0.54
1521 560 1553 653
0.49
800 871 938 936
0.49
820 451 923 527
0.48
828 585 924 704
0.48
1715 722 1762 824
0.42
1521 883 1594 936
0.41
660 449 771 519
0.41
1671 705 1709 801
0.4
412 535 545 645
0.39
629 388 678 438
0.38
1093 444 1148 519
0.37
1615 651 1654 760
0.35
959 332 1020 416
0.35
766 485 858 580
0.3
992 416 1068 502
0.27
Speed: 5.0ms preprocess, 180.7ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     765.55       486.4       857.6      578.16          71]
[     795.79      858.55      941.67      948.89          63]
[     1092.6      443.94      1147.3      519.23          57]
[     1451.8      705.89      1578.9      843.25          54]
[     660.05      447.55      772.34       519.8          51]
[      820.7      451.14      921.24      526.33          50]
[     414.14      534.89      543.16      644.63          24

[     346.37      548.14      486.55      666.58          78]
[     807.48       616.5      910.11      743.48          65]
[     1090.7      457.16      1147.2      531.47          57]
[     529.65      491.31      654.69       591.8          56]
[     1453.2       688.3      1576.1      828.78          54]
[     635.78      450.65      757.56      527.59          51]
[      799.3      459.54      899.57      535.17          50]
[     893.48      490.87      1010.5      578.76          18]
[     532.42      868.74      701.65      952.96          12]

0: 384x640 7 persons, 7 cars, 5 trucks, 178.4ms
887 492 1008 582
0.79
1621 654 1662 767
0.63
628 452 758 531
0.61
1470 539 1510 639
0.57
1521 552 1556 646
0.47
335 552 478 670
0.43
0 320 125 477
0.41
1680 708 1720 814
0.4
1721 729 1766 830
0.38
1522 866 1602 932
0.38
792 460 904 539
0.37
522 490 652 594
0.35
194 407 227 478
0.34
1090 458 1147 534
0.31
1455 688 1576 828
0.3
804 619 908 749
0.29
717 501 817 595
0.28
643 381 691 433
0.28
52

0: 384x640 8 persons, 8 cars, 2 trucks, 171.2ms
853 507 984 594
0.85
1530 541 1565 637
0.67
595 459 713 542
0.65
1477 538 1513 633
0.56
1689 704 1733 819
0.51
1735 734 1783 843
0.47
1639 657 1675 772
0.46
773 666 890 819
0.45
476 497 604 613
0.42
240 574 398 706
0.42
241 576 399 709
0.41
477 498 604 611
0.34
748 475 880 548
0.33
741 477 833 548
0.33
1523 850 1599 909
0.31
1522 849 1607 930
0.28
1296 375 1321 462
0.27
938 413 993 458
0.26
Speed: 5.4ms preprocess, 171.2ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     940.72      413.29      993.03      457.42          81]
[      774.9      667.09      889.46      814.25          65]
[     476.63      499.23      604.57      608.79          56]
[     594.89      459.54      717.18      541.49          51]
[     752.04      473.36       874.1      549.97          50]
[     854.21      505.99      983.35       595.2          18]

0: 384x640 7 persons, 8 cars, 1 truck, 173.9ms
851 510 983 596
0.73
591 460 718 542
0.7

[     816.77      418.85      887.87      479.77          87]
[     130.77      608.25      303.65      754.32          78]
[     732.98      727.38      865.13      910.61          65]
[     425.52       511.6       549.7      634.87          56]
[     559.89      468.23      705.61      556.14          51]
[     711.51      485.42       855.4      570.42          50]
[     812.01      519.86      952.45      613.87          18]

0: 384x640 5 persons, 5 cars, 3 trucks, 96.5ms
805 515 950 618
0.71
703 485 853 573
0.67
1479 529 1519 626
0.61
1536 544 1569 628
0.54
1650 667 1691 779
0.5
418 514 542 644
0.5
728 733 862 912
0.49
1739 741 1794 863
0.48
114 612 293 760
0.43
811 419 888 480
0.39
553 461 706 647
0.27
959 443 1013 512
0.27
1526 831 1589 888
0.26
Speed: 4.3ms preprocess, 96.5ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[     813.26      419.09      886.55      480.52          87]
[     116.88      612.01      292.36       759.4          78]
[     728.65   

[     788.05      426.42      864.36      490.88          87]
[     351.68      526.36      483.09      658.98          85]
[     919.54      436.85      997.06      522.65          77]
[     495.86      561.34      631.63      675.17          71]
[     679.55      796.03       830.6      947.37          65]
[     514.97      483.61      671.97      572.05          51]
[     663.97       498.7      821.33      590.14          50]
[     756.38      540.18       912.6      640.83          18]

0: 384x640 6 persons, 7 cars, 4 trucks, 90.4ms
659 497 819 595
0.83
1481 529 1522 627
0.77
747 541 909 645
0.68
672 816 823 936
0.67
508 487 668 574
0.62
1537 541 1569 625
0.55
1661 674 1701 790
0.48
0 654 173 802
0.44
489 566 621 674
0.43
338 526 478 658
0.41
1744 751 1801 871
0.4
1628 563 1667 653
0.35
1696 680 1746 813
0.35
787 428 864 491
0.34
911 428 1001 528
0.31
0 334 135 471
0.3
1137 356 1189 486
0.26
Speed: 2.8ms preprocess, 90.4ms inference, 2.1ms postprocess per image at shape (1, 3, 384

[     269.12      541.75      422.94      686.46          85]
[     890.22      439.09      976.91      538.72          77]
[     400.14      588.52      548.59       712.3          71]
[     468.96       498.7      636.19      592.43          51]
[     611.79      512.28      776.17      606.07          50]
[     693.52      557.03      868.54      671.63          18]

0: 384x640 9 persons, 10 cars, 1 motorcycle, 91.1ms
462 496 630 598
0.85
614 517 789 609
0.76
685 559 862 678
0.68
1483 524 1518 619
0.65
1532 530 1565 622
0.6
1666 681 1707 800
0.59
1757 765 1802 885
0.53
1711 747 1758 864
0.46
887 443 975 544
0.46
992 490 1058 583
0.46
755 439 836 507
0.42
1702 687 1742 792
0.33
1045 532 1125 639
0.33
1135 439 1185 506
0.32
824 470 889 544
0.32
1633 578 1675 673
0.3
1019 416 1061 477
0.29
401 405 505 464
0.29
190 449 214 504
0.28
1703 691 1754 862
0.27
Speed: 3.4ms preprocess, 91.1ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     992.62      490.57      1057.3 


0: 384x640 6 persons, 12 cars, 2 trucks, 88.6ms
403 511 583 614
0.83
561 529 755 630
0.68
595 587 802 718
0.67
1477 522 1516 620
0.61
1671 694 1710 814
0.59
1530 528 1563 620
0.54
145 560 438 776
0.52
1715 754 1758 876
0.46
860 450 950 557
0.44
1749 772 1804 893
0.42
1129 449 1183 524
0.38
717 451 810 521
0.37
1043 452 1099 518
0.33
926 409 983 474
0.32
978 510 1048 605
0.32
1018 564 1110 677
0.3
1009 430 1066 497
0.28
1064 411 1117 465
0.28
1407 432 1434 493
0.27
145 562 352 737
0.26
Speed: 0.0ms preprocess, 88.6ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     1064.7      412.27      1116.9      462.24         113]
[     1018.6      563.33      1109.4      677.03         110]
[     716.35      451.92      811.23      519.99         109]
[     1036.8      447.46      1101.3       517.6         108]
[     1006.9      428.24      1067.8      498.49         107]
[     978.31      510.41        1047      606.88          94]
[     859.26      450.37      950.07    


0: 384x640 8 persons, 12 cars, 2 trucks, 184.3ms
502 615 732 759
0.78
346 520 538 628
0.72
509 544 716 644
0.67
1669 702 1713 829
0.58
1470 522 1512 614
0.55
1635 586 1679 684
0.48
1034 461 1093 534
0.42
1519 528 1552 613
0.41
1706 706 1747 812
0.38
1402 425 1433 500
0.37
993 596 1095 733
0.36
823 482 915 584
0.35
999 437 1048 507
0.33
750 496 830 578
0.33
1137 369 1193 460
0.31
672 463 762 536
0.29
964 526 1037 632
0.29
168 456 195 513
0.28
834 456 932 517
0.27
645 417 667 463
0.26
1049 416 1109 468
0.26
35 578 286 778
0.26
Speed: 3.6ms preprocess, 184.3ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)
[     832.89      455.09       932.3      519.21         115]
[     992.48      598.06      1095.1      728.98         110]
[     671.05      463.41      765.83      534.77         109]
[     345.74      520.01      537.69      628.72          51]
[     511.61      543.25      715.21      644.24          50]
[     504.92      615.59      732.31       757.2          18

0: 384x640 6 persons, 6 cars, 2 motorcycles, 1 truck, 183.3ms
269 536 478 654
0.69
956 656 1066 810
0.68
372 655 646 814
0.65
445 558 668 678
0.64
1669 712 1715 839
0.6
1635 588 1681 695
0.54
0 715 170 873
0.47
936 556 1018 662
0.46
1737 797 1794 930
0.41
1519 527 1549 612
0.36
1713 772 1757 898
0.29
791 471 900 532
0.28
617 476 723 548
0.28
781 471 899 594
0.27
1467 524 1502 612
0.26
Speed: 4.1ms preprocess, 183.3ms inference, 1.5ms postprocess per image at shape (1, 3, 384, 640)
[     793.97      469.14      899.05      534.16         115]
[     -15.25      710.38      182.41      881.23          71]
[     271.17      536.98      476.46      653.01          51]
[     446.46      560.35      666.51      672.29          50]
[      376.7       655.3      643.34      813.18          18]

0: 384x640 4 persons, 8 cars, 1 motorcycle, 3 trucks, 169.6ms
259 535 470 655
0.72
352 661 626 821
0.67
1668 712 1714 837
0.66
436 559 663 679
0.63
949 659 1062 821
0.53
1634 589 1682 697
0.51
0 723 153 

0: 384x640 6 persons, 12 cars, 1 motorcycle, 2 trucks, 190.4ms
216 701 518 877
0.79
195 546 418 670
0.77
380 571 617 698
0.76
1664 723 1710 851
0.68
911 579 1001 679
0.62
747 480 868 552
0.58
1707 724 1747 819
0.49
1635 604 1681 703
0.41
904 720 1034 908
0.41
1736 813 1784 934
0.4
560 502 647 573
0.37
0 625 102 781
0.36
1016 432 1081 491
0.35
904 721 1034 907
0.33
1461 518 1493 613
0.33
231 430 352 486
0.32
1709 787 1751 912
0.31
391 418 493 468
0.27
625 359 700 400
0.26
1093 490 1159 581
0.26
859 381 962 502
0.26
Speed: 1.6ms preprocess, 190.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     233.63      429.44      351.46      486.73         125]
[      749.9      481.02      866.13      551.34         115]
[     389.85      417.34      493.25      468.53         105]
[     910.65      576.25      1001.3      684.84          94]
[     196.39      546.63      417.04      669.81          51]
[     380.51      573.18       616.3      696.29          50]
[     221.

0: 384x640 7 persons, 9 cars, 1 bus, 1 truck, 172.8ms
123 562 364 695
0.83
51 734 396 934
0.75
303 589 565 720
0.72
844 809 995 938
0.67
1668 731 1711 863
0.64
703 490 834 567
0.59
1505 519 1539 608
0.59
1454 514 1491 609
0.55
1634 605 1679 700
0.52
1227 430 1255 481
0.42
841 445 906 516
0.42
1732 823 1781 934
0.4
471 507 629 594
0.38
265 431 376 494
0.3
625 359 703 407
0.28
238 344 390 460
0.27
1702 788 1750 897
0.26
1473 761 1569 923
0.26
Speed: 9.7ms preprocess, 172.8ms inference, 10.3ms postprocess per image at shape (1, 3, 384, 640)
[     269.38      431.34      371.05      493.21         125]
[        708      490.74      831.95      568.02         115]
[     847.45      798.45      994.38      949.45         110]
[     490.24      508.11      622.61      590.91         109]
[     124.76      562.95      362.67      693.82          51]
[     306.09      588.73      565.01      720.43          50]
[     59.069      737.26      392.54      932.99          18]

0: 384x640 7 persons,

0: 384x640 7 persons, 11 cars, 1 truck, 181.8ms
0 781 236 939
0.81
39 579 295 719
0.77
665 503 799 581
0.71
219 608 508 755
0.66
1672 744 1717 876
0.61
1508 514 1538 603
0.6
1637 613 1685 724
0.58
1450 514 1489 606
0.52
862 654 963 756
0.49
1729 838 1789 937
0.48
980 452 1058 516
0.46
429 513 580 610
0.41
1399 441 1425 517
0.38
813 456 888 526
0.35
1468 745 1561 916
0.34
1702 816 1750 924
0.31
262 430 384 490
0.28
651 358 748 401
0.26
390 419 491 471
0.26
Speed: 4.3ms preprocess, 181.8ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     664.86      503.47      798.56      582.33         115]
[      809.4      440.42      902.56      527.94         111]
[     861.91      652.22      963.14      768.28          94]
[      39.88      578.82      294.88       718.4          51]
[     223.48      609.83      505.36      750.68          50]
[    -24.757      779.53      255.55      944.55          18]

0: 384x640 7 persons, 15 cars, 1 truck, 162.4ms
0 787 213 939
0.8
27 

0: 384x640 7 persons, 12 cars, 1 motorcycle, 3 trucks, 186.9ms
0 595 226 749
0.84
133 627 448 785
0.75
621 514 764 597
0.73
1668 762 1718 894
0.61
1639 624 1689 739
0.61
827 701 940 866
0.59
1701 825 1749 932
0.57
1736 848 1794 937
0.55
0 859 63 935
0.52
1507 518 1536 601
0.51
376 523 522 628
0.48
1140 399 1196 443
0.45
518 573 670 699
0.38
1106 468 1166 545
0.37
1050 554 1122 657
0.35
777 408 889 541
0.28
1451 516 1483 605
0.28
1462 741 1557 910
0.28
260 575 386 639
0.27
1085 465 1165 543
0.27
517 574 670 700
0.26
1260 444 1286 497
0.26
262 434 350 496
0.26
Speed: 5.2ms preprocess, 186.9ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     1462.7      741.93      1556.4      909.84         131]
[     623.08      513.96      763.41      597.46         115]
[      828.6      706.02      939.99      854.48          94]
[     370.89         523      524.36      627.45          87]
[     518.67      575.75      668.44      698.49          77]
[    -11.504      596.23   

[     1023.9      571.08      1116.7      681.23         136]
[     1141.4       403.9        1198      450.19         134]
[      586.4      523.65      734.35      608.23         115]
[     910.81      474.69      1018.7      598.53         113]
[     755.65       417.3      869.42      551.02         111]
[     796.86      746.54      920.15      922.67          94]
[     311.81      532.39      473.87      643.02          87]
[     455.84      592.82      613.94      731.23          77]
[    -13.966      607.21      172.79      760.33          51]
[     52.058      652.78      385.32      817.74          50]

0: 384x640 7 persons, 11 cars, 1 bus, 1 truck, 185.2ms
584 526 730 607
0.78
1668 774 1718 904
0.67
40 652 377 823
0.63
790 756 916 924
0.56
1639 633 1687 742
0.53
1705 840 1756 937
0.51
1504 516 1537 605
0.5
308 533 472 641
0.49
170 488 196 547
0.42
188 591 327 666
0.42
1144 403 1200 451
0.4
1023 573 1115 682
0.4
911 472 1016 603
0.39
0 611 147 752
0.39
1711 777 1759 875
0.35


548 528 703 624
0.8
0 673 320 853
0.71
755 804 897 937
0.71
1670 788 1717 911
0.63
1643 643 1690 755
0.63
1149 406 1204 455
0.56
263 543 424 651
0.51
128 606 281 683
0.51
1700 854 1758 936
0.46
1190 480 1222 550
0.41
1190 479 1223 550
0.36
668 472 707 536
0.35
893 478 1000 612
0.33
392 603 570 764
0.33
1009 596 1105 716
0.32
512 527 566 597
0.29
1441 522 1477 606
0.29
924 558 1010 671
0.27
392 601 571 764
0.27
1504 516 1535 604
0.27
693 357 780 397
0.26
Speed: 4.2ms preprocess, 183.9ms inference, 3.7ms postprocess per image at shape (1, 3, 384, 640)
[     923.66      557.38      1010.1      672.07         147]
[     129.63      605.17      282.05      681.79         137]
[     1007.7      596.65      1106.2      715.38         136]
[     1148.2      405.66      1204.9      454.78         134]
[     548.61      529.97      702.78      622.41         115]
[     893.94       480.5      1000.1      612.47         113]
[     758.28      795.23      895.65       945.4          94]
[     261.

0: 384x640 10 persons, 11 cars, 2 motorcycles, 3 trucks, 191.2ms
505 540 671 638
0.85
1645 649 1701 757
0.68
1667 791 1717 929
0.65
857 489 968 587
0.61
1152 414 1207 460
0.55
717 875 859 936
0.54
186 550 375 670
0.52
1710 794 1768 933
0.52
698 424 828 575
0.44
1198 492 1233 565
0.43
463 538 518 616
0.39
304 600 486 800
0.38
301 598 486 803
0.38
875 426 939 484
0.38
820 438 885 498
0.37
1398 450 1426 538
0.37
0 695 245 874
0.37
904 580 1003 697
0.36
631 479 673 547
0.35
1435 519 1479 610
0.34
149 482 178 550
0.34
997 630 1092 752
0.33
1078 500 1156 586
0.32
1502 518 1532 608
0.31
1000 653 1090 767
0.29
1199 493 1233 565
0.28
Speed: 3.8ms preprocess, 191.2ms inference, 3.6ms postprocess per image at shape (1, 3, 384, 640)
[     874.28      426.55      938.66      481.91         152]
[     820.94      435.51      885.64       500.1         151]
[     903.16      577.77      1006.2      698.14         147]
[      299.7      604.83      488.76      798.99         141]
[     996.28      629

0: 384x640 10 persons, 9 cars, 1 motorcycle, 4 trucks, 192.8ms
1644 658 1709 773
0.73
467 545 638 647
0.71
1656 798 1715 933
0.69
829 504 947 599
0.64
1157 417 1216 465
0.54
669 431 808 584
0.52
0 637 172 860
0.52
126 559 334 684
0.5
999 433 1087 540
0.48
1501 516 1532 605
0.47
797 441 870 506
0.45
412 547 472 634
0.44
1205 509 1242 587
0.4
1000 466 1081 541
0.4
1860 471 1897 543
0.37
1205 505 1242 586
0.36
121 559 332 684
0.35
862 439 932 496
0.34
1398 458 1424 539
0.34
1708 873 1763 936
0.33
1713 803 1772 917
0.31
215 627 446 844
0.31
1850 471 1887 542
0.29
882 599 988 729
0.28
Speed: 3.7ms preprocess, 192.8ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[     994.89      433.82      1090.8      540.14         153]
[      862.9      436.62      932.14      498.54         152]
[     797.99      440.35      869.27      506.74         151]
[    -12.701      642.08      184.83      851.43         150]
[     883.23      599.48      987.76      729.32         147]
[    

0: 384x640 12 persons, 7 cars, 2 motorcycles, 4 trucks, 181.8ms
1643 659 1697 780
0.76
423 557 602 660
0.75
1658 807 1713 936
0.68
790 512 912 608
0.66
635 433 783 595
0.59
1712 812 1777 933
0.58
997 438 1076 547
0.56
1500 515 1529 600
0.51
0 659 90 869
0.51
359 561 414 647
0.51
51 572 270 701
0.5
61 478 88 535
0.48
1159 417 1222 470
0.43
1210 524 1252 612
0.41
52 571 270 699
0.4
1394 464 1431 545
0.4
544 498 597 566
0.36
1439 512 1471 596
0.36
1210 527 1252 612
0.35
230 632 384 748
0.35
133 486 159 551
0.35
110 694 323 882
0.34
1327 433 1353 505
0.3
951 698 1064 874
0.29
773 455 829 510
0.28
Speed: 3.5ms preprocess, 181.8ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     50.872      571.76       270.3      701.57         155]
[     994.59      438.54      1079.3      547.14         153]
[     1159.7      418.15      1222.5      469.32         134]
[     424.77       557.5      601.76      658.63         115]
[     636.04      424.92       783.5      594.71      

0: 384x640 13 persons, 8 cars, 3 motorcycles, 1 truck, 186.7ms
380 565 569 673
0.86
747 519 881 622
0.68
1645 670 1703 792
0.66
1668 814 1719 937
0.66
1711 816 1772 936
0.61
601 437 756 607
0.6
1215 545 1255 635
0.58
1163 423 1232 478
0.56
990 445 1069 524
0.52
1497 514 1529 595
0.48
840 665 948 819
0.47
497 510 550 572
0.46
0 585 211 722
0.45
747 457 821 524
0.44
1433 486 1468 592
0.43
822 442 908 532
0.41
1866 470 1899 543
0.4
278 573 354 672
0.36
522 432 550 488
0.35
1395 466 1422 545
0.31
1334 439 1360 507
0.3
130 777 165 857
0.28
926 742 1049 902
0.27
925 742 1050 920
0.27
128 787 219 879
0.26
Speed: 3.8ms preprocess, 186.7ms inference, 2.5ms postprocess per image at shape (1, 3, 384, 640)
[    -8.5598      584.96      214.86      724.03         155]
[     746.77      457.42      821.43      525.06         151]
[      926.2      741.95      1047.2      904.39         136]
[     1163.1      423.44      1232.1      478.27         134]
[     381.22      565.74      568.52      672.83

[     796.58      444.46      892.22      541.57         152]
[      64.24      672.62       252.8      799.53         149]
[      971.5      450.53      1055.2      536.48         146]
[     896.03      786.78      1029.7      942.43         136]
[     1165.2      423.03      1240.3      480.92         134]
[     335.66      577.37      532.21      688.54         115]
[     571.38      444.96      728.54      613.77         111]
[     708.68      529.08      846.46      633.21         108]
[    -12.765      596.46      162.66      740.74          87]

0: 384x640 11 persons, 12 cars, 1 motorcycle, 4 trucks, 185.9ms
326 579 529 690
0.77
701 528 842 634
0.77
888 803 1028 938
0.72
1666 826 1721 937
0.68
1653 674 1712 800
0.67
564 446 723 617
0.61
1167 418 1246 482
0.58
1716 826 1768 936
0.55
1212 571 1256 661
0.5
793 440 892 543
0.48
1496 507 1534 594
0.42
1394 479 1421 549
0.41
439 519 495 580
0.41
0 597 141 741
0.4
969 452 1053 537
0.39
40 677 240 819
0.38
1429 513 1469 586
0.38
802 708

0: 384x640 14 persons, 7 cars, 1 motorcycle, 1 truck, 188.0ms
280 589 492 708
0.83
656 538 808 649
0.72
1668 831 1721 940
0.69
949 462 1040 542
0.67
1652 685 1712 802
0.67
1176 432 1255 487
0.67
537 448 706 627
0.64
1717 835 1772 936
0.57
1394 481 1419 554
0.55
1499 513 1530 593
0.46
1434 503 1470 587
0.46
1093 501 1136 580
0.41
37 477 63 542
0.39
0 700 171 847
0.38
391 527 442 588
0.36
765 440 856 505
0.33
1209 603 1253 679
0.32
1060 412 1100 463
0.3
1340 439 1363 512
0.29
773 751 909 930
0.29
1869 468 1903 544
0.28
522 429 546 480
0.27
111 494 139 558
0.26
Speed: 3.5ms preprocess, 188.0ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
[     949.83      460.18        1039      542.62         146]
[     1175.2      430.22      1255.2      487.89         134]
[     282.03      588.89      490.59      707.68         115]
[     538.02      449.28      703.83      625.28         111]
[     657.81      538.57       806.7      647.99         108]

0: 384x640 12 persons, 8 c

[     998.01      588.88      1100.3      705.98         161]
[     768.19      666.77      877.31      803.49         157]
[     732.84      451.43      850.44      527.42         152]
[      -18.7      728.03      94.133      867.48         149]
[     733.54       795.9      878.02      946.37         147]
[     928.27      470.92      1026.5      553.54         146]
[     1183.9      433.25        1269      491.43         134]
[     222.57      600.39      445.27      727.97         115]
[     500.23      451.82      686.83      637.67         111]
[     595.45       551.8       758.9      672.25         108]

0: 384x640 10 persons, 11 cars, 2 motorcycles, 3 trucks, 184.2ms
1186 435 1271 490
0.72
722 813 874 938
0.71
209 602 439 736
0.67
923 474 1011 551
0.64
585 549 756 680
0.62
1652 694 1707 823
0.6
1435 505 1466 590
0.56
1394 488 1418 561
0.52
1495 507 1528 590
0.5
722 455 849 527
0.46
761 671 874 814
0.43
1717 847 1774 937
0.42
1197 652 1246 763
0.41
1339 439 1368 515
0.41
1675 

0: 384x640 10 persons, 8 cars, 1 truck, 192.7ms
157 615 396 771
0.77
527 563 710 697
0.72
1654 700 1716 837
0.71
1193 435 1282 492
0.7
899 478 998 566
0.62
732 701 855 860
0.6
1182 703 1236 836
0.58
1496 503 1525 583
0.57
1435 502 1465 585
0.57
1673 849 1729 937
0.56
688 875 833 940
0.56
1721 852 1772 936
0.5
1089 528 1134 615
0.44
1392 487 1416 562
0.42
992 619 1084 741
0.41
689 463 784 524
0.35
22 486 48 548
0.32
459 458 650 645
0.31
1866 470 1899 545
0.28
Speed: 6.5ms preprocess, 192.7ms inference, 3.6ms postprocess per image at shape (1, 3, 384, 640)
[      687.2       460.3      787.81       525.5         168]
[     732.89      703.12      854.84      857.93         157]
[     681.53      862.55      838.37      951.09         147]
[     898.78      478.18      998.08       565.6         146]
[     1192.3      435.19      1282.2      492.85         134]
[     157.09      618.98       395.9      764.27         115]
[     457.48      456.25      650.65      646.04         111]
[    

0: 384x640 12 persons, 10 cars, 1 truck, 175.1ms
449 579 651 725
0.79
1658 709 1722 843
0.78
84 634 343 787
0.77
1206 437 1302 499
0.72
870 493 972 581
0.7
1164 780 1228 927
0.67
690 747 828 929
0.62
1430 501 1464 586
0.6
600 508 667 578
0.6
1392 491 1419 568
0.58
1731 867 1777 937
0.57
1083 545 1127 633
0.56
1494 503 1523 585
0.55
416 470 619 665
0.52
724 501 807 593
0.5
646 472 750 541
0.49
1674 868 1733 936
0.48
1866 472 1900 545
0.35
14 485 39 543
0.31
256 430 345 494
0.27
952 526 1024 626
0.27
211 568 249 627
0.27
1340 439 1363 518
0.26
Speed: 5.1ms preprocess, 175.1ms inference, 3.3ms postprocess per image at shape (1, 3, 384, 640)
[     646.75      472.65      748.36      540.73         168]
[     724.95      505.45      806.08      590.99         167]
[     691.91       748.1      828.23      924.77         157]
[     598.56      506.95       668.8      578.69         151]
[     870.38      492.58      972.02      581.23         146]
[     1206.3      437.69      1300.9      49

[     945.93      543.73      1021.4       636.6         169]
[     588.28       475.7      707.41         552         168]
[     950.01      688.41      1056.8      833.11         161]
[     652.34      789.12      800.87      945.87         157]
[     569.25      511.29       635.8      585.23         151]
[     844.71      501.57      954.35      592.03         146]
[     1220.8      441.91      1320.4      501.83         134]
[      22.07      653.43      289.39      809.33         115]
[     375.31       484.7      601.66      705.78         111]
[     384.06      596.44      599.67      751.89         108]

0: 384x640 15 persons, 10 cars, 1 truck, 184.3ms
8 653 280 815
0.77
1658 719 1718 850
0.76
839 505 949 596
0.71
642 805 797 936
0.7
1222 441 1323 502
0.66
882 637 938 736
0.64
1436 500 1469 584
0.6
368 597 603 757
0.6
1079 560 1119 655
0.57
1496 504 1524 580
0.55
1679 874 1735 936
0.54
74 501 103 562
0.54
1397 502 1426 578
0.53
1146 878 1214 936
0.52
566 512 632 586
0.5
1731 8

[     -5.264      674.77      236.72         839         173]
[     330.19       475.7       549.4      672.28         170]
[     1044.6      434.37        1092      494.02         162]
[     600.82      857.36      760.76      950.46         157]
[     532.86      521.35      593.37      597.71         151]
[     807.08      513.89      925.99       609.3         146]
[       1236       444.9      1343.6      506.56         134]
[     291.57      631.06      537.92      791.62         108]

0: 384x640 9 persons, 11 cars, 1 motorcycle, 1 bus, 1 truck, 183.3ms
1664 728 1723 868
0.83
0 675 220 846
0.73
1239 445 1353 508
0.61
608 881 747 938
0.6
1067 582 1114 681
0.59
1403 505 1431 576
0.58
802 513 921 611
0.56
325 475 541 667
0.53
267 628 534 799
0.51
1439 500 1469 579
0.49
539 488 644 564
0.44
1045 434 1091 497
0.42
1494 502 1523 579
0.41
858 671 906 773
0.4
1741 892 1786 937
0.38
529 524 584 599
0.37
921 736 1038 900
0.35
921 738 1036 901
0.32
858 714 904 779
0.3
655 523 752 619
0.3
25

1668 731 1732 874
0.75
0 699 155 847
0.75
175 653 435 835
0.61
765 523 894 626
0.6
1403 508 1434 574
0.55
1256 447 1368 512
0.53
893 783 1026 933
0.53
1438 503 1466 576
0.52
832 708 885 823
0.49
828 758 883 831
0.49
507 502 587 570
0.46
1127 443 1150 493
0.42
1054 604 1108 703
0.39
272 478 521 692
0.38
1402 504 1442 577
0.38
814 449 907 527
0.37
495 536 541 609
0.37
1493 505 1520 576
0.33
1054 645 1106 708
0.33
1707 896 1750 937
0.3
914 563 998 677
0.3
277 480 520 688
0.28
1288 451 1368 514
0.27
Speed: 4.3ms preprocess, 182.1ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     814.96      451.37      907.52      525.83         175]
[    -6.1971      701.88      161.73      848.62         173]
[     894.29      778.32      1024.6      941.69         172]
[      913.7      564.92      998.37      675.02         171]
[     280.11      481.06       513.1      685.27         170]
[     500.43      500.79      592.28      571.48         168]
[     492.93      535.09     

0: 384x640 9 persons, 11 cars, 4 motorcycles, 1 bus, 1 truck, 185.4ms
1668 742 1742 891
0.85
54 689 332 884
0.81
1273 450 1402 518
0.78
713 536 860 641
0.72
1048 634 1097 739
0.63
900 582 990 693
0.58
0 729 80 840
0.56
215 488 490 722
0.52
794 809 849 901
0.52
572 543 681 643
0.5
859 858 997 937
0.49
788 465 888 536
0.46
1852 471 1895 559
0.46
45 503 78 567
0.45
1435 495 1465 576
0.45
792 757 852 869
0.42
791 789 854 889
0.41
795 756 850 840
0.39
1051 682 1095 750
0.32
1410 498 1448 575
0.31
333 421 383 466
0.29
382 408 485 464
0.29
215 490 484 724
0.29
0 733 120 840
0.29
1048 665 1097 742
0.28
1126 452 1152 504
0.27
Speed: 6.8ms preprocess, 185.4ms inference, 3.2ms postprocess per image at shape (1, 3, 384, 640)
[     215.35      490.64      484.42      722.03         180]
[     787.29      458.18      889.04      538.44         175]
[    -3.2229      732.98      84.186      835.61         173]
[     859.33      847.07      995.63      948.48         172]
[     218.21      489.64     

[     376.93      409.72      484.68      467.05         183]
[     145.43      503.15      434.05      757.01         180]
[      761.8      465.85      864.81       547.1         175]
[     883.09      604.43      977.07      730.69         171]
[     525.02      552.94      639.38      659.04         167]
[     660.67      551.06      815.66      668.29         146]
[     1295.1      451.09      1423.6      518.81         134]
[    -19.408      729.29      232.93      933.38         108]

0: 384x640 9 persons, 11 cars, 1 motorcycle, 2 trucks, 190.5ms
1668 750 1729 894
0.82
742 824 809 938
0.71
651 551 815 671
0.71
0 731 201 932
0.65
136 502 418 764
0.64
1487 493 1513 570
0.64
757 465 863 546
0.51
880 608 976 734
0.5
1036 677 1090 784
0.48
1041 727 1086 803
0.45
1298 453 1429 518
0.43
1422 649 1497 770
0.41
1411 502 1455 571
0.4
1126 463 1149 517
0.39
1429 491 1461 571
0.36
1433 481 1467 568
0.31
378 410 487 464
0.31
1297 454 1369 510
0.29
1120 386 1175 427
0.29
1193 407 1235 455
0.2

0: 384x640 5 persons, 13 cars, 1 motorcycle, 1 truck, 186.6ms
584 568 771 701
0.74
0 779 63 931
0.73
1673 767 1735 905
0.73
1022 717 1080 847
0.71
1484 499 1512 569
0.55
58 517 361 783
0.49
732 475 838 556
0.46
1120 470 1147 529
0.46
1370 562 1463 650
0.43
1529 443 1556 511
0.37
782 434 858 494
0.35
1197 412 1246 462
0.35
467 569 582 683
0.33
1355 462 1450 523
0.32
328 425 379 464
0.31
1026 779 1075 859
0.3
377 408 477 465
0.28
252 424 338 487
0.27
1021 471 1071 533
0.26
886 442 953 500
0.26
Speed: 4.4ms preprocess, 186.6ms inference, 4.0ms postprocess per image at shape (1, 3, 384, 640)
[     780.27      432.09      859.19       494.9         189]
[     375.91      407.92      479.45      464.68         183]
[     59.323      515.51      361.64      784.94         180]
[     730.86      475.12      838.11      556.92         175]
[     465.65      568.95      584.42      681.36         167]
[     588.35      568.82      767.78      697.88         146]
[     249.93       424.5      342

0: 384x640 6 persons, 8 cars, 2 motorcycles, 1 truck, 190.2ms
1674 773 1748 926
0.81
0 535 275 827
0.74
685 489 800 571
0.66
488 591 704 744
0.63
997 795 1065 933
0.6
827 688 936 834
0.49
997 794 1062 882
0.47
1344 460 1482 533
0.44
392 589 517 718
0.41
735 440 827 514
0.4
999 864 1062 937
0.39
1111 478 1144 548
0.37
945 508 982 574
0.35
1822 474 1854 539
0.34
864 452 929 514
0.32
1889 454 1919 562
0.3
372 412 475 466
0.28
Speed: 4.5ms preprocess, 190.2ms inference, 3.1ms postprocess per image at shape (1, 3, 384, 640)
[     863.76      452.26      927.92      513.84         190]
[     733.13      441.04      827.44      512.17         189]
[     685.64      490.59      799.55      571.14         175]
[    -8.9958      536.11      279.92      825.13         170]
[     827.25      686.96       935.7      832.86         169]
[      391.9      591.04      517.82      714.73         167]
[     492.14      594.28       701.4      740.81         146]
[     1346.6      460.75      1479.1     

[     836.22      455.69      906.77      524.52         190]
[      641.8      503.89      775.81      591.05         175]
[    -15.165      558.96      205.06      856.37         170]
[     791.52      732.48      913.27      908.87         169]
[     320.06      613.26      453.02      748.48         167]
[      388.6      625.03      628.68      792.92         146]

0: 384x640 5 persons, 10 cars, 2 motorcycles, 1 bus, 1 truck, 186.3ms
1668 785 1736 935
0.83
637 511 765 593
0.72
1355 464 1496 545
0.65
0 565 183 847
0.65
371 628 624 805
0.62
1434 532 1474 634
0.55
831 463 900 529
0.54
784 737 908 905
0.52
982 891 1032 937
0.44
927 523 969 600
0.4
1103 497 1135 569
0.39
990 488 1049 566
0.34
439 497 590 645
0.3
1102 499 1134 570
0.3
1433 509 1483 635
0.29
927 441 986 512
0.28
310 616 443 752
0.28
1225 428 1280 484
0.26
1394 475 1494 545
0.26
Speed: 5.4ms preprocess, 186.3ms inference, 3.5ms postprocess per image at shape (1, 3, 384, 640)
[     831.48      460.21      901.85      528.4

[     281.44      659.01      544.96      845.55         201]
[     914.12      450.84      974.22      523.98         196]
[     391.04      510.79      547.15      660.94         194]
[     812.44      472.75      883.83      539.43         190]
[       1236       429.3      1301.1      491.46         187]
[     608.68      511.39      768.18       603.7         175]
[    -15.994      610.57      132.91      860.42         170]
[     758.82       777.7      889.57      940.53         169]
[     245.75      632.91       391.3      778.79         167]
[     985.37      501.27      1048.9      581.04         162]
[     1375.4      467.99      1518.2      539.08         134]

0: 384x640 5 persons, 5 cars, 1 motorcycle, 4 trucks, 191.1ms
1679 802 1744 936
0.84
750 791 886 937
0.75
265 664 530 856
0.67
1377 469 1523 535
0.64
1449 547 1485 641
0.63
597 511 775 609
0.62
1099 514 1133 590
0.62
1099 512 1132 586
0.5
0 662 103 845
0.49
918 538 960 629
0.49
809 474 883 539
0.47
0 582 110 850
0.3

[     169.42       697.6      458.06       900.9         201]
[        335      521.31      502.46      689.75         194]
[     789.21      481.94      864.94       550.8         190]
[     320.08      432.58      378.85      475.54         184]
[    -13.027      563.77      59.867      836.25         180]
[     564.83      522.41      739.36      620.85         175]
[     719.22      838.56      866.35      950.08         169]
[     178.39      662.44      338.98      795.97         167]
[     1393.4      470.01      1539.9      540.03         134]

0: 384x640 6 persons, 15 cars, 2 motorcycles, 2 trucks, 190.9ms
1686 814 1767 936
0.78
151 701 445 909
0.71
719 864 861 937
0.56
1462 552 1501 648
0.54
325 516 498 690
0.48
1797 476 1830 539
0.48
165 671 329 800
0.47
0 609 36 839
0.46
1490 488 1544 535
0.44
786 485 863 554
0.44
1394 471 1518 537
0.44
893 466 959 538
0.41
377 418 485 473
0.39
562 521 734 619
0.39
1099 530 1134 617
0.34
222 434 337 486
0.33
903 609 949 665
0.33
1137 404 12

0: 384x640 7 persons, 13 cars, 2 motorcycles, 1 truck, 189.8ms
42 738 368 938
0.84
1702 824 1781 937
0.8
1426 476 1570 556
0.73
531 537 703 640
0.73
596 483 714 556
0.65
770 490 856 566
0.57
97 697 273 808
0.57
281 528 463 707
0.54
1105 543 1142 627
0.46
1483 567 1519 654
0.46
891 590 945 687
0.41
1198 501 1232 561
0.41
260 436 347 491
0.39
893 620 946 695
0.37
1805 477 1833 539
0.33
1370 546 1462 641
0.32
1085 442 1136 512
0.31
1377 456 1411 547
0.31
339 435 392 477
0.3
1197 500 1232 560
0.28
630 483 715 558
0.28
388 423 492 477
0.27
229 442 273 484
0.26
Speed: 6.3ms preprocess, 189.8ms inference, 3.5ms postprocess per image at shape (1, 3, 384, 640)
[     1085.5      443.09      1135.6      510.45         214]
[     45.185       735.8      365.38      943.51         201]
[     596.53      482.68      715.81      555.69         197]
[     282.11      529.83      461.12      706.42         194]
[      770.6      489.72      853.82      565.47         190]
[     630.92      486.53      

0: 384x640 7 persons, 11 cars, 4 motorcycles, 1 truck, 182.5ms
1440 479 1593 561
0.83
1710 841 1779 939
0.74
1496 570 1533 669
0.71
743 490 834 580
0.63
490 553 656 654
0.55
215 542 410 738
0.55
1102 576 1144 664
0.53
556 494 682 572
0.52
1102 568 1143 662
0.51
870 677 921 753
0.51
0 780 252 935
0.49
349 439 399 477
0.48
866 631 927 733
0.45
1044 434 1086 505
0.43
868 641 924 745
0.41
1093 466 1141 525
0.41
1204 516 1241 575
0.39
1165 414 1226 465
0.34
1331 445 1411 514
0.34
926 412 971 454
0.32
12 489 40 553
0.27
0 456 42 553
0.27
1203 513 1242 576
0.26
Speed: 5.2ms preprocess, 182.5ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     1092.9       461.4      1141.8      527.14         214]
[    -20.541      770.53      269.07      944.49         201]
[     560.09      493.99       683.1       570.9         197]
[     218.45      544.57      408.87      734.68         194]
[     745.19      494.06      833.99      578.61         190]
[     348.11      437.49      4

0: 384x640 7 persons, 10 cars, 3 motorcycles, 2 trucks, 1 boat, 178.3ms
1726 850 1795 936
0.72
451 547 620 666
0.7
1462 479 1598 550
0.68
159 553 358 763
0.65
1205 528 1249 587
0.62
535 505 655 583
0.6
1514 576 1553 670
0.57
1098 587 1144 683
0.57
852 726 902 805
0.43
0 735 152 904
0.42
1174 413 1243 470
0.41
1800 479 1831 538
0.39
850 668 909 746
0.38
1095 466 1144 534
0.37
849 669 909 778
0.36
1368 438 1457 507
0.35
1579 510 1889 642
0.31
337 551 459 643
0.3
0 733 151 936
0.3
0 806 148 936
0.29
957 490 996 572
0.29
1101 606 1143 685
0.27
353 436 406 475
0.26
Speed: 5.0ms preprocess, 178.3ms inference, 3.4ms postprocess per image at shape (1, 3, 384, 640)
[     339.85      551.12      457.95      644.32         217]
[     1094.6      466.35      1144.1      533.33         214]
[    -22.149      738.04      169.04      913.59         201]
[     1175.9      414.99      1239.3      468.85         199]
[     534.25      505.55      656.39      581.45         197]
[     160.25      555.75 

0: 384x640 6 persons, 14 cars, 3 motorcycles, 1 truck, 180.4ms
1526 585 1568 682
0.78
1738 862 1818 937
0.69
483 518 616 598
0.67
1490 482 1606 556
0.64
83 575 299 787
0.6
816 771 880 883
0.6
403 570 582 689
0.58
1179 417 1254 475
0.56
1208 532 1253 607
0.52
1093 627 1142 725
0.46
817 728 882 810
0.45
0 788 63 925
0.4
914 423 965 469
0.37
1096 654 1141 730
0.34
44 460 73 549
0.33
1099 477 1149 545
0.32
972 430 1021 490
0.32
403 584 550 682
0.31
413 426 510 480
0.28
962 568 1044 670
0.28
262 440 370 488
0.28
1805 480 1830 535
0.27
783 479 900 585
0.26
272 437 408 499
0.26
Speed: 6.6ms preprocess, 180.4ms inference, 3.3ms postprocess per image at shape (1, 3, 384, 640)
[     972.34      430.75      1020.5      490.05         221]
[     915.15      423.17      965.75       468.6         216]
[       1099      475.47      1149.7      544.56         214]
[     -16.07      778.99      77.358      926.37         201]
[     1180.8      417.69      1252.3      474.05         199]
[     482.22  

0: 384x640 7 persons, 12 cars, 3 motorcycles, 1 truck, 1 boat, 185.0ms
1541 593 1582 692
0.77
0 595 226 829
0.72
423 526 580 608
0.71
1190 418 1270 480
0.64
1509 481 1613 550
0.62
775 799 852 933
0.6
350 583 547 726
0.5
1593 511 1904 642
0.5
955 586 1044 688
0.49
1749 882 1821 936
0.48
417 424 519 479
0.45
1094 663 1140 748
0.39
1209 534 1258 622
0.38
901 522 945 605
0.37
371 440 421 476
0.37
1095 721 1141 781
0.32
916 423 974 473
0.32
658 526 758 615
0.32
1213 540 1258 623
0.31
202 578 335 678
0.31
971 443 1020 497
0.3
818 453 891 516
0.29
1094 664 1143 777
0.28
779 800 848 903
0.27
Speed: 5.0ms preprocess, 185.0ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     971.57      441.69      1019.6      496.83         221]
[     203.66      579.39       334.8      677.06         217]
[     917.56      423.34      973.12      472.85         216]
[     1510.3      480.92        1613      549.73         211]
[       1191      418.58      1269.3       479.7         199]
[

1549 599 1591 704
0.69
0 611 155 827
0.67
392 535 535 620
0.61
736 878 804 937
0.6
125 594 267 696
0.53
325 584 501 706
0.52
1081 759 1128 834
0.5
1204 422 1276 482
0.49
1512 481 1612 549
0.48
372 439 421 476
0.46
943 598 1035 716
0.45
961 442 1011 504
0.43
1079 709 1131 827
0.42
1208 547 1255 637
0.41
912 422 970 478
0.4
1595 510 1903 643
0.36
863 538 911 625
0.35
417 424 519 479
0.33
1207 548 1255 637
0.33
1753 891 1820 937
0.33
1111 405 1153 464
0.32
330 671 418 776
0.31
63 484 88 548
0.29
298 441 377 502
0.28
866 534 913 614
0.27
1431 453 1465 555
0.26
Speed: 7.3ms preprocess, 184.0ms inference, 3.0ms postprocess per image at shape (1, 3, 384, 640)
[     125.65       592.8      266.97      695.83         226]
[      960.3      441.77      1012.4      503.55         221]
[      912.2      423.81      969.26      477.85         216]
[     1512.1       480.9      1614.5       549.3         211]
[     1201.2      419.88      1279.2       484.5         199]
[     385.96      533.87     

[     930.02      626.25      1023.4       744.4         228]
[     775.65      461.67       864.8      537.22         227]
[     946.79      452.24      999.06      514.31         221]
[     1534.8      484.06      1619.9      549.45         211]
[     1207.9      428.87        1284      492.33         199]
[     337.14      542.52      490.34      632.79         197]
[     -16.42      634.66      102.56       859.5         194]
[     583.96      546.99      692.28      642.76         190]
[     364.84      438.65      421.81      481.59         184]
[     415.87      424.21      524.08       481.8         183]
[     237.92       608.3      456.67      758.21         175]
[     1538.1      485.53      1689.9      550.94         134]

0: 384x640 8 persons, 9 cars, 1 motorcycle, 3 trucks, 1 boat, 189.8ms
1557 607 1600 721
0.74
320 545 481 638
0.74
1212 430 1285 492
0.69
1544 490 1693 551
0.62
1058 773 1116 916
0.61
1444 487 1481 581
0.48
1503 488 1535 557
0.47
1204 594 1251 663
0.41
0 6

[     157.72      616.32      406.47      819.96         233]
[     911.26      652.94      1008.4      768.23         228]
[     757.36      468.77      835.19      538.81         227]
[     931.14      464.64      985.36      523.95         221]
[    -11.688       625.2      131.55      732.64         217]
[     1214.4      432.56      1291.7      494.41         199]
[     268.79      554.35      435.95      651.51         197]
[     360.53      438.11      417.29      480.55         184]
[     161.07      627.43      405.01      810.79         175]
[     1551.8      491.81      1695.4      554.11         134]

0: 384x640 7 persons, 14 cars, 2 motorcycles, 2 trucks, 170.5ms
1565 621 1610 730
0.71
1208 432 1296 494
0.67
1032 838 1101 936
0.65
250 554 430 661
0.61
154 617 395 777
0.59
1447 490 1481 583
0.56
1559 493 1689 554
0.56
755 467 832 542
0.49
1193 599 1248 681
0.46
909 657 1008 779
0.42
413 425 523 484
0.41
1162 497 1192 567
0.41
1204 501 1240 574
0.41
927 465 986 524
0.38
891 

[     104.04      623.27       345.6      796.46         233]
[     493.63       563.1      614.44      668.42         231]
[     888.08      684.21      994.19      822.39         228]
[     732.34      474.83      808.93      547.73         227]
[     913.36      469.91      972.71      533.54         221]
[       1226      437.02      1302.2      498.51         199]
[     195.39       562.6      386.97      668.33         197]
[     412.04      425.19       519.4      483.26         183]
[     1567.3      500.56      1692.7      570.22         134]
[     284.51      435.33      410.35      496.25         125]

0: 384x640 7 persons, 9 cars, 4 motorcycles, 3 trucks, 1 boat, 181.4ms
1563 633 1612 744
0.77
1220 436 1302 498
0.65
887 686 992 833
0.56
186 566 384 674
0.56
815 507 861 579
0.45
910 466 968 535
0.44
97 631 340 798
0.43
411 424 520 483
0.41
1450 487 1483 571
0.4
690 598 760 685
0.39
1485 489 1519 556
0.38
1151 503 1182 585
0.36
1199 512 1234 586
0.35
97 630 340 798
0.34
1188 

[     722.93      446.15       807.1      496.66         238]
[     855.41      726.22      972.12      885.55         228]
[     695.34      490.45      777.85      564.48         227]
[     875.48      469.79      954.57      549.25         216]
[     1221.5      440.74      1311.5      502.85         199]
[     121.51      579.55         317      682.68         197]
[     356.92      438.88      414.02      485.12         184]
[     412.07      427.35      516.17       485.2         183]
[     4.3408      647.58      271.38      829.47         175]

0: 384x640 5 persons, 12 cars, 2 motorcycles, 1 truck, 183.3ms
1570 645 1616 761
0.71
1219 442 1317 503
0.65
850 734 967 900
0.65
106 582 306 686
0.59
0 652 259 836
0.57
688 492 771 563
0.52
773 523 823 597
0.5
718 450 801 500
0.48
1174 634 1230 729
0.46
1144 533 1176 619
0.44
1015 505 1073 593
0.4
1451 493 1485 579
0.37
417 581 548 692
0.32
772 514 825 597
0.32
592 621 676 720
0.31
308 439 414 494
0.28
864 444 947 506
0.28
928 418 977 4

0: 384x640 6 persons, 15 cars, 3 motorcycles, 1 truck, 1 boat, 93.5ms
1574 658 1627 784
0.78
0 672 185 872
0.68
50 598 246 709
0.67
1137 552 1172 643
0.61
1190 545 1230 636
0.61
816 781 952 937
0.59
1160 674 1219 787
0.59
1228 449 1327 512
0.54
739 532 786 613
0.51
352 595 490 707
0.47
1451 502 1496 597
0.45
410 431 514 487
0.39
738 527 786 613
0.37
517 545 634 636
0.35
1586 518 1891 651
0.32
655 499 744 584
0.31
1558 465 1579 529
0.3
1008 524 1067 613
0.3
282 443 401 510
0.28
853 471 929 567
0.28
520 646 621 746
0.28
688 455 770 508
0.27
1366 535 1446 634
0.27
286 445 376 503
0.27
1366 535 1448 636
0.26
256 443 374 500
0.26
Speed: 4.1ms preprocess, 93.5ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     518.91      543.24      631.98      639.98         239]
[     1007.5      509.56      1067.5      613.86         234]
[    -10.329      674.28       191.9      869.21         233]
[     354.42       594.6      488.69       707.5         231]
[     818.49      776.

[     662.32      455.52      743.86      510.47         238]
[    -12.921      686.76      127.93      864.63         233]
[     785.41      820.55      927.71      948.17         228]
[     831.77      493.48      907.07      576.35         221]
[     1234.1      451.05        1338      515.27         199]
[    -6.1826      610.04      194.89       726.1         197]
[     407.08      431.66      511.14       487.7         183]

0: 384x640 6 persons, 13 cars, 5 motorcycles, 87.9ms
0 613 184 727
0.8
779 838 922 938
0.79
1573 670 1624 793
0.74
0 695 107 858
0.66
1123 585 1163 683
0.57
1184 565 1224 658
0.53
1238 456 1347 519
0.52
829 501 904 581
0.51
1142 718 1206 841
0.45
1204 416 1254 464
0.43
658 454 743 512
0.43
696 548 750 632
0.41
395 657 536 804
0.4
1144 753 1204 843
0.39
909 425 963 474
0.37
1147 763 1195 848
0.35
1107 383 1158 433
0.35
1462 505 1494 603
0.34
1030 567 1104 675
0.33
407 432 511 487
0.29
279 446 410 512
0.28
1144 712 1206 833
0.28
91 487 115 549
0.27
615 500 703 

0: 384x640 6 persons, 16 cars, 6 motorcycles, 1 truck, 1 boat, 112.8ms
1580 690 1634 809
0.78
1249 459 1366 527
0.7
1178 581 1223 683
0.6
292 735 405 854
0.58
636 452 717 514
0.55
1113 658 1153 728
0.51
955 432 1061 503
0.5
816 460 926 554
0.45
0 628 127 763
0.44
955 436 1037 500
0.42
1582 540 1885 658
0.41
0 741 38 876
0.41
900 432 962 483
0.38
802 500 883 595
0.35
1110 617 1155 723
0.35
1463 505 1492 594
0.35
278 452 366 517
0.34
661 556 715 649
0.33
94 491 116 547
0.29
1096 386 1156 441
0.29
580 518 712 608
0.29
1016 588 1097 698
0.28
1091 465 1136 526
0.28
1132 820 1182 906
0.27
819 460 918 528
0.27
291 766 400 856
0.27
406 440 510 490
0.27
1045 415 1090 460
0.26
1440 498 1470 571
0.26
1128 772 1193 897
0.26
Speed: 0.0ms preprocess, 112.8ms inference, 2.6ms postprocess per image at shape (1, 3, 384, 640)
[    -2.1579      749.43       39.52      865.93         251]
[     1099.9      387.84      1154.4      436.41         250]
[      955.2      434.54      1033.1      501.38        

[     940.61      436.84      1017.8      498.33         245]
[     615.63      455.95      697.08       517.1         238]
[      885.9      437.61      948.48      489.93         237]
[     538.94      534.92      638.88      623.53         227]
[      796.2      464.67       906.2      557.15         216]
[     1257.1      464.54      1377.1      532.18         199]
[    -14.346      645.84      78.898      775.59         197]
[     399.75      442.88      505.57      494.13         183]

0: 384x640 6 persons, 13 cars, 3 motorcycles, 3 trucks, 189.5ms
1579 698 1631 831
0.81
615 458 693 519
0.57
1308 484 1384 537
0.54
1175 607 1217 700
0.51
401 441 505 494
0.49
887 439 947 489
0.49
1260 469 1383 533
0.44
1211 432 1255 483
0.43
1259 466 1335 527
0.42
1460 521 1493 609
0.39
1084 691 1133 793
0.39
796 466 895 544
0.37
158 762 286 904
0.37
277 455 367 519
0.35
1357 542 1425 632
0.35
0 651 56 771
0.34
533 534 632 627
0.34
1106 804 1173 934
0.33
940 437 1052 515
0.32
1082 682 1132 777
0.31

0: 384x640 4 persons, 17 cars, 4 motorcycles, 3 trucks, 1 boat, 176.8ms
1583 708 1634 839
0.76
1047 775 1105 866
0.73
1035 432 1081 482
0.61
1086 855 1157 936
0.61
925 453 1000 513
0.52
871 452 933 500
0.5
1274 473 1395 536
0.47
603 460 677 522
0.43
43 786 176 929
0.43
780 477 879 566
0.42
732 542 824 631
0.4
490 553 594 647
0.39
1354 549 1424 637
0.38
1460 513 1494 627
0.36
400 443 506 498
0.36
1343 495 1409 544
0.33
505 411 563 482
0.32
924 451 1046 526
0.32
274 455 361 506
0.31
950 530 1030 688
0.3
1296 476 1410 545
0.29
569 584 634 679
0.29
0 375 139 507
0.28
1273 473 1359 532
0.28
276 455 387 518
0.28
1576 534 1884 665
0.26
1045 744 1103 864
0.26
1165 633 1216 717
0.26
979 643 1074 760
0.26
Speed: 9.9ms preprocess, 176.8ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     1273.5       472.7        1357      533.57         263]
[     1034.6       432.6      1081.3      480.74         255]
[     1352.6       549.2      1424.2      635.94         246]
[       133

0: 384x640 3 persons, 14 cars, 2 motorcycles, 4 trucks, 1 boat, 181.1ms
1585 726 1638 852
0.8
1288 474 1425 544
0.61
444 561 556 658
0.57
859 453 926 506
0.56
593 461 660 524
0.54
1164 664 1209 730
0.5
909 464 980 525
0.46
966 671 1061 803
0.44
276 458 364 525
0.43
0 698 250 891
0.42
1161 665 1211 769
0.39
1031 437 1080 490
0.39
1001 850 1064 937
0.37
255 615 403 735
0.37
748 487 856 569
0.36
1577 538 1898 667
0.35
396 445 502 501
0.34
1092 401 1140 447
0.34
937 599 1018 707
0.3
276 456 401 517
0.29
907 461 999 530
0.28
520 602 593 698
0.28
341 458 401 501
0.26
0 385 128 514
0.26
Speed: 8.9ms preprocess, 181.1ms inference, 2.3ms postprocess per image at shape (1, 3, 384, 640)
[     1287.1      474.71      1426.5      544.29         266]
[     1031.9      437.33      1079.3      488.89         255]
[     907.59      464.52       983.8      525.49         245]
[     257.07      616.23      402.35      732.66         239]
[     590.93      461.34       660.3      523.71         238]
[    

1584 734 1640 866
0.76
889 468 970 539
0.55
725 496 837 568
0.52
846 453 911 512
0.47
397 450 497 502
0.45
1302 485 1441 550
0.44
1150 700 1207 819
0.43
1089 407 1136 451
0.35
0 747 159 918
0.34
398 573 508 673
0.34
343 460 399 501
0.34
194 633 352 764
0.33
919 619 1005 731
0.33
0 732 162 917
0.33
1566 530 1900 669
0.32
659 567 764 662
0.32
1022 444 1075 497
0.32
469 613 547 714
0.3
469 647 547 716
0.3
1224 453 1272 506
0.29
0 385 131 533
0.29
786 546 829 617
0.28
193 633 350 763
0.28
937 476 1028 549
0.28
935 704 1050 846
0.26
Speed: 4.9ms preprocess, 178.8ms inference, 8.6ms postprocess per image at shape (1, 3, 384, 640)
[     725.62      494.05      835.84      570.62         265]
[    0.65644      389.13      127.95      528.08         262]
[     1022.4      443.39      1074.5      498.77         255]
[     1088.2      407.16      1136.5      450.99         250]
[     888.51      468.96      969.62      538.02         245]
[     194.56      633.63      349.37      761.46         2

0: 384x640 3 persons, 14 cars, 3 motorcycles, 2 trucks, 2 boats, 95.3ms
1585 743 1639 875
0.79
1019 451 1073 513
0.54
415 633 498 747
0.53
395 447 500 506
0.53
1141 733 1201 854
0.51
0 749 64 931
0.49
699 503 815 579
0.48
1565 543 1869 670
0.47
869 473 962 547
0.43
1140 773 1200 874
0.41
1082 407 1137 458
0.41
757 554 801 628
0.39
1793 534 1918 607
0.37
588 460 635 517
0.35
1142 733 1201 813
0.35
830 470 892 519
0.33
0 382 136 521
0.33
623 579 733 680
0.32
238 462 349 513
0.3
341 462 398 504
0.3
696 505 777 584
0.29
1067 506 1121 583
0.28
984 406 1036 460
0.27
134 647 301 780
0.26
Speed: 4.7ms preprocess, 95.3ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     134.41      646.49      299.92      781.35         272]
[    -6.8616      774.03      71.698      911.15         270]
[     699.13      504.12       814.5      577.54         265]
[    0.71126      381.93      135.56      524.77         262]
[     1019.4      452.44      1072.9      511.45         255]
[    

0: 384x640 2 persons, 18 cars, 1 motorcycle, 2 boats, 92.4ms
1589 756 1641 889
0.72
64 663 244 804
0.62
1014 450 1069 513
0.61
665 508 792 585
0.55
888 784 1013 938
0.54
846 482 940 556
0.52
888 668 983 795
0.52
815 464 883 521
0.49
1126 779 1193 916
0.46
1567 545 1869 671
0.45
392 449 495 504
0.44
363 639 454 762
0.39
285 593 411 691
0.39
578 586 693 694
0.36
1233 456 1288 515
0.36
1339 489 1451 565
0.35
341 460 394 500
0.35
1083 409 1133 461
0.33
585 455 632 517
0.3
268 461 339 518
0.3
1795 533 1919 606
0.29
947 491 1007 559
0.26
846 480 985 568
0.26
Speed: 2.9ms preprocess, 92.4ms inference, 0.0ms postprocess per image at shape (1, 3, 384, 640)
[     341.32      459.76      394.29      500.21         269]
[     1013.9      450.13      1068.8      513.86         255]
[     848.66      480.34      973.18      565.04         252]
[     1081.8      408.94      1133.7      461.15         250]
[     1231.6      456.97      1287.4      515.29         248]
[     584.32      456.18       631

[     2.6929      684.46      194.33      849.94         272]
[     638.23      513.53      745.24      596.18         265]
[     1360.6      487.26      1459.4      551.41         263]
[     1010.4      456.23        1067      516.97         255]
[     1235.4         457      1292.7      516.08         248]
[      829.1      484.15      928.88      567.97         245]
[     585.11      451.67       630.3      509.01         238]
[     797.97      465.07      871.37      525.62         237]
[     234.89      601.26      368.19      703.28         227]
[     539.92       596.9      663.19      710.28         221]
[     1362.7      487.35      1521.4      569.59         199]
[     251.74      461.47      344.39         517         184]

0: 384x640 4 persons, 20 cars, 2 motorcycles, 3 trucks, 2 boats, 99.5ms
1592 754 1645 895
0.74
1115 824 1185 938
0.7
1010 455 1068 518
0.65
1456 509 1532 549
0.57
856 832 988 937
0.57
1474 557 1505 638
0.56
1237 457 1294 515
0.53
635 512 746 595
0.5
1362 

0.36
169 608 314 721
0.34
1561 535 1872 656
0.32
606 525 703 606
0.32
858 715 967 867
0.31
777 464 863 533
0.3
1852 532 1919 615
0.27
342 455 391 496
0.26
Speed: 3.2ms preprocess, 94.0ms inference, 1.7ms postprocess per image at shape (1, 3, 384, 640)
[      863.3      596.99      957.29       713.5         278]
[     610.78      519.25      740.57      605.63         265]
[    0.51619       375.4      137.64      516.51         262]
[     1006.1      457.85      1064.5      521.81         255]
[     1243.8      455.63      1300.6      512.03         248]
[     801.34      486.98      916.81      575.92         245]
[    -11.251      689.02      137.47      828.19         239]
[     779.42      465.24       860.3      532.01         237]
[     858.55      716.39      966.45       866.2         234]
[     1385.5      482.45      1552.7      554.29         199]
[     247.67      457.14      355.88      519.05         184]
[     389.62      438.46       493.1      498.54         183]

0: 


0: 384x640 2 persons, 13 cars, 1 motorcycle, 1 truck, 81.7ms
1597 762 1661 908
0.8
565 522 714 616
0.74
999 460 1064 527
0.7
770 495 891 584
0.66
1419 481 1581 561
0.64
199 702 307 826
0.59
1332 527 1410 606
0.58
419 621 566 763
0.53
1481 545 1512 632
0.53
1050 527 1115 616
0.46
90 620 249 743
0.46
830 753 948 920
0.44
849 619 944 750
0.41
592 432 636 486
0.41
756 462 850 533
0.36
262 450 388 515
0.34
1067 412 1125 461
0.27
Speed: 3.0ms preprocess, 81.7ms inference, 1.0ms postprocess per image at shape (1, 3, 384, 640)
[     1331.9      525.94      1410.9      607.04         280]
[     848.11      620.32      943.75      743.06         278]
[     565.82       522.3      713.45      615.73         265]
[     999.36      460.91      1063.6      526.78         255]
[     771.15      494.78      889.64      585.01         245]
[     591.76      433.09       635.8      485.09         238]
[     758.13       463.8      845.94      533.98         237]
[     92.389      621.58      247.49    

[     1329.1      519.58      1407.2      600.55         280]
[     827.53      637.68      929.76      768.65         278]
[     972.87      401.04      1026.2       462.8         273]
[     526.38      526.41      683.64      623.66         265]
[     994.96      462.64        1062      532.51         255]
[     1066.3      410.82      1123.1      462.01         250]
[     739.93      496.94      866.24      594.09         245]
[     807.16      787.36      936.48      941.31         234]
[     1047.2      532.36      1113.1      626.39         229]
[     21.721      635.22      185.71      756.57         227]
[     1428.3      476.06      1586.2      552.78         199]

0: 384x640 2 persons, 13 cars, 3 motorcycles, 2 trucks, 90.9ms
516 527 679 627
0.79
797 801 932 935
0.76
1437 477 1585 550
0.74
1608 771 1666 916
0.72
993 462 1062 536
0.68
732 494 864 595
0.62
124 735 240 861
0.61
1482 548 1516 637
0.52
825 642 924 777
0.52
1329 518 1407 601
0.48
2 639 176 757
0.44
1066 414 1123 46

0: 384x640 3 persons, 12 cars, 1 motorcycle, 3 trucks, 85.4ms
987 463 1057 544
0.8
1615 777 1677 926
0.79
769 855 907 940
0.72
475 528 647 633
0.69
800 669 910 812
0.67
696 507 835 602
0.61
1055 408 1118 460
0.59
1484 473 1584 539
0.59
1328 511 1413 592
0.54
1486 541 1517 632
0.54
273 670 441 827
0.44
972 411 1025 461
0.43
50 770 189 885
0.43
1431 483 1468 557
0.34
0 647 107 770
0.31
605 419 648 473
0.29
1042 544 1111 639
0.28
1280 446 1355 512
0.28
274 670 441 829
0.26
Speed: 2.0ms preprocess, 85.4ms inference, 2.0ms postprocess per image at shape (1, 3, 384, 640)
[     1329.5      511.57      1411.4      592.12         280]
[     800.68      667.17       909.2      809.95         278]
[     972.55      410.73      1024.8       461.7         273]
[     477.07      529.28      645.77      631.39         265]
[     987.44      465.24      1057.1      541.86         255]
[     1056.2      408.43      1117.4      459.54         250]
[     1281.3      448.33      1351.6      511.49        

In [47]:
import cvzone
import math
model=YOLO("yolov8l.pt")
classNames =["person", "bicycle", "car", "motorbike", "aeroplane", "bus", "train", "truck", "boat", "traffic light", 
             "fire nydrant", "stop sign", "parking meter", "bench", "bird", "cat", "dog", "horse", "sheep", 
             "cow", "elephant", "bear", "Zebra", "giraffe", "backpack", "umbrella", "handbag" "tie", 
             "suitcase", "frisbee", "skis", "snowboard", "sports ball", "kite", "haseball bat",
             
             "baseball glove", "skateboard", "surfboard", "tennis racket", "bottle", "wine glass",
             "cup", "fork", "knife", "spoon", "bowt", 
             "banana", "apple", "sandwich", "orange", "broccoli", "carrot", "hot dog",
             "pizza", "donut", "cake", "chair", "sofa", "pottedplant", "bed", 
             "diningtable", "toilet", "tvmonitor", "Laptop", "mouse", 
             "remote", "keyboard", "cell phone", "cellphone", "oven", 
             "toaster", "sink", "refrigeraton", "book", "clock", "vase", 
             "scissors", "teddy bear", "hair drier","toothbrush"]


tracker=Sort(max_age=20,min_hits=3,iou_threshold=0.3)
limits=[223,500,1473,500]
totalCount=[]

cap=cv2.VideoCapture('11.mp4')
cap.set(3,640)
cap.set(4,480)
mask=cv2.imread("mask_car.png")
while True:
    success,img=cap.read()
    mask_resized = cv2.resize(mask, (img.shape[1], img.shape[0]))  # Match width and height of img
    imgRegion = cv2.bitwise_and(img, mask_resized)

#     imgRegion=cv2.bitwise_and(img,mask)
    results=model(imgRegion,stream=True)
    detections=np.empty((0,5))
    for r in results:
        boxes=r.boxes
        for box in boxes:
            #bounding box
            
            x1,y1,x2,y2=box.xyxy[0]

            x1,y1,x2,y2=int(x1),int(y1),int(x2),int(y2)
#             cv2.rectangle(img,(x1,y1),(x2,y2),(0,255,0),3)
            w,h=x2-x1,y2-y1
#             bbox=int(x1),int(y1),int(w),int(h)
            
            
            
            print(x1,y1,x2,y2)

            cvzone.cornerRect(img,(x1,y1,w,h),l=15,colorR=(0, 0, 255),colorC=(0, 255, 255))
#             confidence
            conf=math.ceil((box.conf[0]*100))/100
                            
            print(conf)
            cls=int(box.cls[0])
            currentclass=classNames[cls]
            if currentclass=='car'or currentclass=='bus'or currentclass=='truck' or currentclass=='motorbiker' and conf>0.3:
                
#                 cvzone.putTextRect(img,f'{classNames[cls]} {conf}',(max(0,x1),max(15,y1)),scale=1,thickness=1,colorT=(0, 0, 255),
#                                colorR=(255, 0,0),offset=3)
                cvzone.cornerRect(img,(x1,y1,w,h),l=15,rt=1,colorR=(0, 0, 255),colorC=(0, 255, 255))
                currentArray=np.array([x1,y1,x2,y2,conf])
                detections=np.vstack((detections,currentArray))
                
                
    resultTracker=tracker.update(detections)
    cv2.line(img,(limits[0],limits[1]),(limits[2],limits[3]),(0,0,250),thickness=5)
    for result in resultTracker:
        x1,y1,x2,y2,id=result
        x1,y1,x2,y2=int(x1),int(y1),int(x2),int(y2)
        print(result)
        w,h=x2-x1,y2-y1
        
        cvzone.cornerRect(img,(x1,y1,w,h),l=15,rt=1,colorR=(100, 255, 255),colorC=(0, 150, 255))
        cvzone.putTextRect(img,f'{classNames[cls]} {conf}',(max(0,x1),max(35,y1)),scale=1,thickness=2,colorT=(0, 0, 255),
                               colorR=(255, 0,0),offset=3)
        cx,cy=x1+w//2,y1+h//2
        cv2.circle(img,(cx,cy),5,(255,0,255),cv2.FILLED)
        
        if limits[0]<cx<limits[2] and limits[1]-20<cy<limits[1]+20:
            if totalCount.count(id)==0:
                
            
                totalCount.append(id)
    cvzone.putTextRect(img,f'COUNT:{len(totalCount)}',(50,50),scale=1,thickness=2,colorT=(0, 0, 255),
                               colorR=(255, 0,0),offset=3)
        
    cv2.imshow("images",img)
#     cv2.imshow("imagesRegion",imgRegion)
    cv2.waitKey(1)
        # Wait for 1ms, check if 'q' key is pressed
    key = cv2.waitKey(1)
    if key == 27:  # 'q' key to quit
        break


cap.release()
cv2.destroyAllWindows()



0: 640x384 7 persons, 1 car, 1 motorcycle, 1 truck, 558.5ms
112 815 186 977
0.86
414 915 509 1053
0.83
271 728 322 864
0.81
417 522 447 609
0.76
706 480 784 531
0.71
306 688 352 762
0.66
288 555 329 645
0.65
248 702 284 818
0.63
559 517 666 626
0.57
430 984 500 1085
0.38
Speed: 3.0ms preprocess, 558.5ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)
[        559         517         666         626        1757]
[        706         480         784         531        1756]

0: 640x384 7 persons, 2 cars, 1 motorcycle, 682.3ms
112 817 185 983
0.86
423 901 517 1032
0.82
274 728 322 861
0.79
417 523 448 607
0.74
249 700 285 817
0.66
289 552 328 648
0.61
560 515 665 623
0.59
305 686 351 758
0.55
439 974 500 1079
0.55
706 480 784 527
0.52
Speed: 4.0ms preprocess, 682.3ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
[     559.88      515.12      665.12      622.88        1757]
[     706.73      479.55      783.27      527.45        1756]

0: 640x384 8 pers

576 480 670 565
0.84
156 1359 292 1531
0.8
99 841 179 1019
0.79
297 703 352 845
0.78
542 727 604 836
0.77
254 692 300 809
0.68
290 653 339 722
0.61
288 563 325 658
0.58
431 518 461 597
0.5
Speed: 2.0ms preprocess, 695.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
[     576.42      478.02      669.59      566.07        1757]

0: 640x384 8 persons, 1 car, 1 handbag, 534.6ms
96 843 176 1024
0.81
575 480 667 559
0.81
300 704 351 845
0.78
252 691 302 809
0.76
546 719 609 826
0.72
428 518 458 597
0.65
170 1339 301 1504
0.65
292 653 339 728
0.6
287 567 324 659
0.52
155 935 182 979
0.31
Speed: 1.9ms preprocess, 534.6ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
[     575.94      477.27      667.81      561.79        1757]

0: 640x384 8 persons, 1 car, 1 motorcycle, 556.2ms
95 849 177 1008
0.83
576 479 665 557
0.82
300 705 351 843
0.79
551 710 609 816
0.78
254 691 301 809
0.68
186 1318 307 1480
0.68
428 517 457 596
0.62
294 653 331 728
0.59
285 566 3

0: 640x384 9 persons, 1 handbag, 531.4ms
73 878 151 1047
0.83
0 1036 55 1253
0.78
300 674 349 804
0.77
406 496 436 589
0.75
223 671 272 791
0.73
591 584 641 674
0.63
341 1010 436 1205
0.56
250 562 293 658
0.45
138 971 165 1016
0.35
260 640 305 752
0.33
Speed: 2.0ms preprocess, 531.4ms inference, 2.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 7 persons, 1 car, 1 fire hydrant, 1 handbag, 537.0ms
70 879 151 1042
0.86
0 1034 58 1242
0.77
299 673 346 799
0.77
405 496 436 589
0.75
224 673 271 789
0.74
592 579 641 672
0.71
257 641 303 711
0.44
137 971 164 1018
0.37
563 479 638 506
0.32
343 997 443 1193
0.31
Speed: 3.0ms preprocess, 537.0ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 10 persons, 1 handbag, 598.5ms
65 880 149 1050
0.87
0 1032 66 1248
0.81
403 497 435 591
0.76
592 575 641 659
0.76
221 672 269 789
0.75
297 671 345 800
0.74
348 989 440 1173
0.51
246 566 287 658
0.49
254 643 301 717
0.41
130 977 161 1020
0.33
254 643 303 761
0.31


[     1028.5      935.22      1077.7      1119.9        1759]

0: 640x384 6 persons, 1 car, 1 motorcycle, 1 handbag, 541.8ms
231 620 283 750
0.84
0 889 62 1073
0.84
357 759 427 901
0.75
163 616 218 714
0.62
313 479 345 543
0.54
164 655 215 747
0.48
46 992 70 1034
0.48
1023 941 1079 1128
0.44
136 541 183 647
0.4
Speed: 2.0ms preprocess, 541.8ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)
[     1024.6      937.01      1077.6      1129.4        1759]

0: 640x384 5 persons, 1 motorcycle, 1 handbag, 705.7ms
227 618 277 748
0.83
0 889 57 1075
0.79
352 751 425 895
0.71
157 613 210 712
0.56
158 661 210 751
0.51
37 987 64 1038
0.43
309 479 340 542
0.38
Speed: 2.9ms preprocess, 705.7ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 384)

0: 640x384 6 persons, 1 car, 1 handbag, 642.6ms
219 610 269 738
0.82
0 887 53 1080
0.74
351 739 423 885
0.69
152 607 197 705
0.43
33 986 59 1033
0.37
123 539 169 645
0.36
1016 944 1079 1151
0.33
303 479 335 539
0.3
Speed: 2.0ms 